<script setup>
const page_title = 'Annales khâgne A/L LSH';

let meta_description = 'Les annales de toutes les matières de prépas littéraires lshs.';
meta_description += ' Les sujets et rapports des dernières années.';

const breadcrumb_items = [
  {
    label: 'Annales',
    to: '/annales',
    url: 'https://fr.notyloops.com/annales',
  },
  {
    label: 'CPGE',
    to: '/annales/cpge',
    url: 'https://fr.notyloops.com/annales/cpge',
  },
  {
    label: 'khâgne A/L LSH',
  },
];

useSchema({
  name: page_title,
  description: meta_description,
  breadcrumb_items,
});

useSeoMeta({
  title: `${page_title} | NotyLoops`,
  description: meta_description,
});

// useGoogleTag();
</script>

<template>
  <!-- app/pages/annales/cpge/khagne-al-lsh/index.vue -->
  <UContainer class="max-w-xl">
    <UBreadcrumb
      class="mb-8"
      :items="breadcrumb_items"
    />

    <h1>
      Annales khâgne A/L LSH
    </h1>

    <ul class="list-disc list-inside">
      <li>
        <ULink
          to="/annales/cpge/khagne-al-lsh/francais"
          class="text-primary"
        >
          Français
        </ULink>
      </li>
      <li>
        <ULink
          to="/annales/cpge/khagne-al-lsh/geographie"
          class="text-primary"
        >
          Géographie
        </ULink>
      </li>
      <li>
        <ULink
          to="/annales/cpge/khagne-al-lsh/histoire"
          class="text-primary"
        >
          Histoire
        </ULink>
      </li>
      <li>
        Langue B (BCE) :
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-allemand"
          class="text-primary"
        >
          allemand
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-anglais"
          class="text-primary"
        >
          anglais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-arabe"
          class="text-primary"
        >
          arabe
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-chinois"
          class="text-primary"
        >
          chinois
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-espagnol"
          class="text-primary"
        >
          espagnol
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-grec-ancien"
          class="text-primary"
        >
          grec ancien
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-italien"
          class="text-primary"
        >
          italien
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-japonais"
          class="text-primary"
        >
          japonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-latin"
          class="text-primary"
        >
          latin
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-polonais"
          class="text-primary"
        >
          polonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-portugais"
          class="text-primary"
        >
          portugais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-classique/lb-russe"
          class="text-primary"
        >
          russe
        </ULink>
      </li>
      <li>
        Langue vivante étrangère :
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-allemand"
          class="text-primary"
        >
          allemand
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-anglais"
          class="text-primary"
        >
          anglais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-arabe"
          class="text-primary"
        >
          arabe
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-chinois"
          class="text-primary"
        >
          chinois
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-espagnol"
          class="text-primary"
        >
          espagnol
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-italien"
          class="text-primary"
        >
          italien
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-japonais"
          class="text-primary"
        >
          japonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-polonais"
          class="text-primary"
        >
          polonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-portugais"
          class="text-primary"
        >
          portugais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/lve-russe"
          class="text-primary"
        >
          russe
        </ULink>
      </li>
      <li>
        <ULink
          to="/annales/cpge/khagne-al-lsh/philosophie"
          class="text-primary"
        >
          Philosophie
        </ULink>
      </li>
      <li>
        Spécialité :
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-allemand"
          class="text-primary"
        >
          allemand
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-arts"
          class="text-primary"
        >
          arts
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-anglais"
          class="text-primary"
        >
          anglais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-arabe"
          class="text-primary"
        >
          arabe
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-chinois"
          class="text-primary"
        >
          chinois
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-cinema"
          class="text-primary"
        >
          cinéma
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-espagnol"
          class="text-primary"
        >
          espagnol
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-francais"
          class="text-primary"
        >
          français
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-geographie"
          class="text-primary"
        >
          géographie
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-grec"
          class="text-primary"
        >
          grec
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-histoire"
          class="text-primary"
        >
          histoire
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-italien"
          class="text-primary"
        >
          italien
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-japonais"
          class="text-primary"
        >
          japonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-latin"
          class="text-primary"
        >
          latin
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-musique"
          class="text-primary"
        >
          musique
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-philosophie"
          class="text-primary"
        >
          philosophie
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-polonais"
          class="text-primary"
        >
          polonais
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-russe"
          class="text-primary"
        >
          russe
        </ULink>
        |
        <ULink
          to="/annales/cpge/khagne-al-lsh/specialite-theatre"
          class="text-primary"
        >
          théâtre
        </ULink>
      </li>
    </ul>
  </UContainer>
</template>
