# For local development only
services:
  test-notyloops-pg-service:
    image: postgres:latest
    container_name: test-notyloops-pg-container
    restart: always
    environment:
      POSTGRES_USER: test_notyloops_user
      POSTGRES_PASSWORD: dummypassword123
      POSTGRES_DB: test_notyloops_db
    ports:
      - "2346:5432"
    volumes:
      - ./test_notyloops_pg_volume:/var/lib/postgresql
