-- CREATE TABLE shared_notes (
--   id UUID PRIMARY KEY DEFAULT uuidv7(),
--   created_at TIMESTAMPTZ NOT NULL DEFAULT now() ,
--   updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--   source_user_id UUID,
--   source_collection_id UUID,
--   destination_user_id UUID,
--   status TEXT -- pending, accepted, granted, revoked
-- );

-- CREATE TRIGGER update_shared_notes_timestamp
-- BEFORE UPDATE ON shared_notes
-- FOR EACH ROW
-- EXECUTE FUNCTION update_timestamp();
