'use strict';

const EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS = 72;
const PASSWORD_RESET_TOKEN_DURATION_IN_HOURS = 1;
// const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1440;
const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1;
const USER_STATUS_PENDING = 'pending';
const USER_STATUS_TIER_1 = 'tier_1';
const USER_STATUS_TIER_2 = 'tier_2';
const USER_STATUS_UNVERIFIED = 'unverified';
const USER_TOKEN_CONNECT = 'connect';
const USER_TOKEN_RESET_PASSWORD = 'reset_password';
const USER_TOKEN_VALIDATE_EMAIL = 'validate_email';

export {
  EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS,
  PASSWORD_RESET_TOKEN_DURATION_IN_HOURS,
  SESSION_RENEWAL_THRESHOLD_IN_MINUTES,
  USER_STATUS_PENDING,
  USER_STATUS_TIER_1,
  USER_STATUS_TIER_2,
  USER_STATUS_UNVERIFIED,
  USER_TOKEN_CONNECT,
  USER_TOKEN_RESET_PASSWORD,
  USER_TOKEN_VALIDATE_EMAIL,
};
