'use strict';

const EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS = 72;
const PASSWORD_RESET_TOKEN_DURATION_IN_HOURS = 1;
const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1440;
// const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1;
const USER_TOKEN_CONNECT = 'connect';
const USER_TOKEN_RESET_PASSWORD = 'reset_password';
const USER_TOKEN_VALIDATE_EMAIL = 'validate_email';

const LIST_PREFERENCE_AREA_LIST = Object.freeze([
  'note',
  'tag',
  'collection',
]);

const LIST_PREFERENCE_AREA_SET = new Set(LIST_PREFERENCE_AREA_LIST);

export {
  EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS,
  LIST_PREFERENCE_AREA_LIST,
  LIST_PREFERENCE_AREA_SET,
  PASSWORD_RESET_TOKEN_DURATION_IN_HOURS,
  SESSION_RENEWAL_THRESHOLD_IN_MINUTES,
  USER_TOKEN_CONNECT,
  USER_TOKEN_RESET_PASSWORD,
  USER_TOKEN_VALIDATE_EMAIL,
};
