'use strict';

const EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS = 72;
const PASSWORD_RESET_TOKEN_DURATION_IN_HOURS = 1;
const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1440;
// const SESSION_RENEWAL_THRESHOLD_IN_MINUTES = 1;
const USER_TOKEN_CONNECT = 'connect';
const USER_TOKEN_RESET_PASSWORD = 'reset_password';
const USER_TOKEN_VALIDATE_EMAIL = 'validate_email';

const LIST_PREFERENCE_AREA_LIST = Object.freeze([
  'note',
  'tag',
  'collection',
]);

const LIST_PREFERENCE_AREA_SET = new Set(LIST_PREFERENCE_AREA_LIST);

const PREMIUM_ACCESS_PRE_TAX_AMOUNT_IN_CENTS = 6000;

const COLLECTION_PAYMENT_TYPE = 'collection';
const PREMIUM_PAYMENT_TYPE = 'premium_access';

export {
  COLLECTION_PAYMENT_TYPE,
  EMAIL_VALIDATION_TOKEN_DURATION_IN_HOURS,
  LIST_PREFERENCE_AREA_LIST,
  LIST_PREFERENCE_AREA_SET,
  PASSWORD_RESET_TOKEN_DURATION_IN_HOURS,
  PREMIUM_ACCESS_PRE_TAX_AMOUNT_IN_CENTS,
  PREMIUM_PAYMENT_TYPE,
  SESSION_RENEWAL_THRESHOLD_IN_MINUTES,
  USER_TOKEN_CONNECT,
  USER_TOKEN_RESET_PASSWORD,
  USER_TOKEN_VALIDATE_EMAIL,
};
